name: CD - monitoring

# 起動条件
on:
  # firebase/functions ディレクトリ配下に変更あり && develop or main ブランチに push された時
  push:
    paths:
      - "gcp/cloud_monitoring/**"
    branches:
      - develop
      - main
  # GitHubActions のページから手動で実行できるようにする(https://docs.github.com/ja/actions/managing-workflow-runs/manually-running-a-workflow)
  workflow_dispatch:

jobs:
  parameter:
    name: My Checkout Job
    runs-on: ubuntu-latest
    steps:
      - name: Set parameter
        id: random-number-generator
        run: echo "::set-output name=random-number::$(echo '12345')"
        shell: bash
      - name: Result env
        run: >
          echo output parameter is ${{ steps.random-number-generator.outputs.random-number }}
